version: 2
updates:
  
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "npm"
    versioning-strategy: auto
    groups:
      angular-packages:
        patterns:
          - "@angular/*"
        exclude-patterns:
          - "@angular/cli"
      dev-dependencies:
        dependency-type: "development"
